### ISSUE TITLE
Set colorama version to >=0.4.5

### ISSUE THREAD

**Issue by fuster92** [okken/pytest-check#102]
Latest refactor adds a dependency to `colorama >= 0.4.6`, meanwhile awscl sets a `colorama <= 0.4.5`
https://github.com/okken/pytest-check/blob/b96e3654c57c1e1dcd14690848a06426bf9ad1af/pyproject.toml#L19

This is currently breaking `pip` when installing `pytest-check` alongside `awscli` as it cannot resolve a valid `colorama` package to install.

Is it posible to reduce the version?

**Comment by fuster92** [comment]
Opened a PR in case the issue is accepted #103

**Comment by okken** [comment]
That's gonna be a problem. I'm using just_fix_windows_console(), which was introduced in 0.4.6.
However, I'm considering pulling colorama out. 
Stay tuned.

**Comment by okken** [comment]
I'm a dork. I don't need to use this because pytest already fixed it for windows, and because this is a pytest plugin, we can assume pytest did it right, so... hold tight.

**Comment by okken** [comment]
Version 1.2.1 removes colorama as a dependency

**Comment by fuster92** [comment]
Thank you very much!
