### ISSUE TITLE
The results of the two functions are different, and the with statement block does not support test_demo_black_with_2

### ISSUE THREAD

**Issue by gcil125** [okken/pytest-check#123]
![image](https://user-images.githubusercontent.com/67992830/226848595-038f3957-5d1a-49ab-8373-60527bc459f5.png)

**Comment by gcil125** [comment]
test_ demo_ black_ with_ 1 output 2, test_ demo_ black_ with_ 2 No output. The with statement treats the within the statement block as a whole, making soft assertions instead of each assertion as a whole?

**Comment by okken** [comment]
Unfortunately, no.   
Within the with block, assert still stops execution.  
Any statements after a failing assert, up to the end of the with block, will not be run.  
I wasn't explicit in the README about that, but the example with multiple `with check` blocks, each with one `assert`, was intended to show that.

Sorry for the confusion.
