### ISSUE TITLE
Add possibility to print full trace

### ISSUE THREAD

**Issue by Le0nRoy** [okken/pytest-check#124]
Sometimes it is required to see all traces instead of pseudo-trace only. So it would be great to have possibility to configure what output should be printed

**Comment by okken** [comment]
I'm not sure I'd like the complexity that would add to the code. 
However, I'm willing to consider, if you have an example of how it could be implemented.

**Comment by okken** [comment]
some changes coming in 2.2.0, not huge changes, but I'm incorporating the full traceback information

**Comment by okken** [comment]
2.2.0 is published

**Comment by Le0nRoy** [comment]
Thank you!
