### ISSUE TITLE
Add option to skip additional levels in pseudotraceback

### ISSUE THREAD

**Issue by mbergen** [okken/pytest-check#130]
It would be great to have an option for the various check functions to skip additional traceback levels.
This would benefit situations where the actual check is encapsulated into a helper function (e.g. to check multiple things at a time, and not directly done in the test method.

Example:
checkResponse could be omitted in the pseudotraceback
```python
def test_1():
  response = apiCall()
  checkResponse(response, expected)

def checkResponse(response, expected):
  check.equal(response.status, 200)
  check.equal(response.content, expected)
```

**Comment by okken** [comment]
Interesting idea.  
I'd probably like it to utilize [`__tracebackhide__`](https://docs.pytest.org/en/7.1.x/example/simple.html?highlight=__tracebackhide__#writing-well-integrated-assertion-helpers).

Is this something you'd like to implement?

**Comment by okken** [comment]
fix in progress

**Comment by okken** [comment]
version 2.2.0 honors __tracebackhide__

**Comment by mbergen** [comment]
Thank you!
