### ISSUE TITLE
Feature request: own error message for showing in a short test summary info

### ISSUE THREAD

**Issue by OlgaSolod** [okken/pytest-check#133]
Hello!
I couldn't understand, how to get my own messages about errors in short summary info. Now it is empty, I see only: FAILED: {test_name}, without additional info. I tried to use msg=, which i found in context-manager.py but nothing has changed. Could you tell me please, how to output my messages about errors in the short test summary info?

**Comment by okken** [comment]
I'd like this to work. I'll try to look into it when I find some time. 
If someone else wants to try to fix this, go for it. :)
