### ISSUE TITLE
Feature request: Add new test outcome status ?

### ISSUE THREAD

**Issue by harmin-parra** [okken/pytest-check#138]
The current behavior is that failed check yields a `failed` test status.

The minor problem I see with that is that I would like to quickly identified "pure" failed tests from those with just failed checks.

Perhaps we can achieve that by adding a new test outcome status ? (ex: `cfailed` for check failed)

**Comment by okken** [comment]
This plugin has not defined any new test results outcomes for pytest. 
I don't know if it's even possible.
However, even if it was, I don't think I'd want to do that.  
The intent of the plugin wasn't to have a different kind of failure, but simply to perform all checks before stopping the test, and reporting all failed checks. And marking the test as failed if any checks failed.
