### ISSUE TITLE
pytest-check does not FAIL in fixtures

### ISSUE THREAD

**Issue by reddypdl** [okken/pytest-check#14]
Why is pytest.check does NOT report failures in fixtures, but assert does it.

e.g.
`
import pytest
import pytest_check as check

@pytest.fixture()
def before():
    **check.is_true(False, "I am failed - before")**
    print('\nbefore each test')
 
def test_1(before):
    **check.is_true(False, "I am failed - test_1")**
    print('test_1()')
`

============================= test session starts =============================
platform win32 -- Python 2.7.15, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('c:\\Temp\\.hypothesis\\examples')
rootdir: c:\Temp, inifile:
plugins: rerunfailures-6.0, repeater-0.1.1, repeat-0.8.0, random-0.2, json-0.4.0, cov-2.6.1, check-0.3.4, assume-1.2.2, hypothesis-4.14.2
collected 1 item

test3.py F                                                               [100%]

================================== FAILURES ===================================
___________________________________ test_1 ____________________________________
FAILURE: I am failed - test_1
assert False
 +  where False = bool(False)
  test3.py, line 10, in test_1() -> check.is_true(False, "I am failed - test_1")
------------------------------------------------------------
**Failed Checks: 1**
---------------------------- Captured stdout setup ----------------------------

before each test
---------------------------- Captured stdout call -----------------------------
test_1()
========================== 1 failed in 0.13 seconds ===========================

**Comment by okken** [comment]
Thanks for catching that.
Working on the fix.

**Comment by okken** [comment]
fixed in 0.3.5
