### ISSUE TITLE
Linux environment does not have version 2.1.5

### ISSUE THREAD

**Issue by WaterLoran** [okken/pytest-check#142]
Linux environment does not have version 2.1.5

![image](https://github.com/okken/pytest-check/assets/52927459/249bb518-9ae0-420c-93ea-7c87e0cbea4e)

**Comment by WaterLoran** [comment]
[root@localhost ~]# python3
Python 3.6.8 (default, Jun 20 2023, 11:53:23)

**Comment by okken** [comment]
mainline pytest-check, like pytest, supports Python 3.7 and above. 

See pyproject.toml: 
requires-python = ">=3.7"

**Comment by WaterLoran** [comment]
thank you very much
