### ISSUE TITLE
"'NoneType' object is not subscriptable" when you use retry decorator

### ISSUE THREAD

**Issue by nozokada** [okken/pytest-check#15]
We're getting the error when validation fails inside a function using `retry` (https://pypi.org/project/retry/). It seems that the `contextlist` gets `None` as it goes through the `retry` function calls in the stack to collect the failure logs. 
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
<decorator-gen-54>:2: in _
    ???
utils/retrier.py:24: in retry_decorator
    rv = retry_call(f, fargs, fkwargs, exceptions, tries, delay, max_delay, backoff, jitter, log)
.eggs/retry-0.9.2-py3.6.egg/retry/api.py:101: in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
.eggs/retry-0.9.2-py3.6.egg/retry/api.py:33: in __retry_internal
    return f()
internal/fixtures/connectors_verification.py:87: in _
    validate_incidents(incidents_with_entity_name, expected_detectors, creation_time)
internal/fixtures/connectors_verification.py:122: in _
    check_detector_matches_in_incidents(incidents, expected_detectors)
internal/fixtures/anon.py:137: in _
    f'Mismatch between expected detectors {expected_detectors} and actual detectors {actual_detectors}'
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

level = 9

    def get_full_context(level):
        (_, filename, line, funcname, contextlist) = inspect.stack()[level][0:5]
        filename = os.path.relpath(filename)
>       context = contextlist[0].strip()
E       TypeError: 'NoneType' object is not subscriptable

.eggs/pytest_check-0.3.4-py3.6.egg/pytest_check/check_methods.py:170: TypeError`
```

Here is what `inspect.stack()[level][0:5]` looks like when the error occurs. 
![Capture](https://user-images.githubusercontent.com/2498905/57166780-7c664d00-6db8-11e9-8957-be70931b13b1.PNG)

**Comment by okken** [comment]
I've never used retry, I'll take a look.

**Comment by okken** [comment]
hmmmm. this looks like a defect for retry.
Not sure what this has to do with pytest-check

However, if the defect is that retry and pytest-check don't play nice together, you are correct.
pytest-check allows the test proper to pass and changes the result in a hook function.
retry would have to utilize pytest hook functions to tell if a test failed, not it's current method.

However, pytest-rerunfailures is compatible with pytest-check

**Comment by KjellMorgenstern** [comment]
I am currently investigating a similar error:

```
level = 3

    def get_full_context(level):
        (_, filename, line, funcname, contextlist) = inspect.stack()[level][0:5]
        filename = os.path.relpath(filename)
>       context = contextlist[0].strip()
E       TypeError: 'NoneType' object is not subscriptable

/usr/local/lib/python3.8/dist-packages/pytest_check/check_methods.py:294: TypeError
```

The following plugins are used:
```
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /tester, configfile: pytest.ini
plugins: icdiff-0.6, check-2.1.4, xdist-3.2.0, forked-1.6.0, reporter-0.5.2, html-3.1.1, metadata-2.0.1, xvfb-2.0.0, random-order-1.0.4, reporter-html1-0.8.2
```

**Comment by okken** [comment]
Sorry @KjellMorgenstern, I can't reproduce your issue.

**Comment by okken** [comment]
If you can reproduce it, please:
1. open a new issue. this one is closed
2. provide a full test file that causes the problem
3. minimal plugin list that causes the problem.

It is possible that there are other plugins that are not compatible with pytest-check, but I don't really want to hunt them down.

Thanks.
