### ISSUE TITLE
[v2.2.3] ExceptionRepr creation is not compatible with pytest < 7.3.

### ISSUE THREAD

**Issue by mchromin** [okken/pytest-check#153]
Hi,

It seems that pytest-check relies on latest pytest version, but in our environment we have frozen pytest version 7.2.2.
Line introduced in 2.2.3 
`reprtraceback = ExceptionRepr(reprcrash, excinfo)`
is not possible to be executed in pytest < 7.3 as ExceptionRepr was changed there
[ExceptionRepr 7.3 changes](https://github.com/pytest-dev/pytest/commit/310b67b2271cb05f575054c1cdd2ece2412c89a2#diff-ac2099a172465905236568f8c175328fb75ebc1b80ce39f4799e61373d355418L999)

7.2.2
```
>>> from _pytest._code.code import ExceptionRepr
>>> ExceptionRepr(None, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ExceptionRepr.__init__() takes 1 positional argument but 3 were given
```

7.3.0+
```
>>> from _pytest._code.code import ExceptionRepr
>>> ExceptionRepr(None, None)
ExceptionRepr(reprtraceback=None, reprcrash=None, sections=[])
```

Could you please take a look? Thank you!

**Comment by okken** [comment]
Try updating pytest-check to 2.2.4 (latest) and see if that helps.

**Comment by mchromin** [comment]
Seems to be fixed ;)
Thank you for quick response!
