### ISSUE TITLE
Linux environment can only download and install libraries up to version 2.1.5

### ISSUE THREAD

**Issue by WaterLoran** [okken/pytest-check#165]
![image](https://github.com/okken/pytest-check/assets/52927459/c59605b9-e921-4807-9570-4f6613936c59)

But I need to use the function pytest_checkl. fail ()

![image](https://github.com/okken/pytest-check/assets/52927459/026ab3e8-4c9f-4ea0-a81b-3c24643b8213)

**Comment by okken** [comment]
I'm not sure what you're really seeing. 
Could you post the output of `pip install pytest-check`?
If that doesn't end up grabbing 2.3.1, then try `pip install pytest-check==2.3.1`.
Please post the output of both.
That might narrow down the problem.

**Comment by WaterLoran** [comment]
Thank you very much for your guidance. I have successfully updated pytest check to 2.3.1 in the Linux environment
![image](https://github.com/okken/pytest-check/assets/52927459/4538356c-dfeb-4d87-9f48-4c5d66e30197)

**Comment by WaterLoran** [comment]
Found the problem, pip install pytest check cannot be updated to the corresponding version
