### ISSUE TITLE
How to flip back to asserts for pdb/debugging

### ISSUE THREAD

**Issue by hangtwenty** [okken/pytest-check#19]
Is there a way to switch to strict/eager assertion fail mode, so that one can use `--pdb` on demand?

**Comment by hangtwenty** [comment]
It seems like `-p no:check` actually does the trick, but perhaps this issue can serve as documentation :)

**Comment by okken** [comment]
I really don't see how -p no:check would work.
At least, I can't get it to work.

What I can get to work is -x, or --exitfirst

**Comment by okken** [comment]
Probably should add that to the documentation

**Comment by okken** [comment]
old, and original submitter has a workaround
