### ISSUE TITLE
Detailed logging for failures

### ISSUE THREAD

**Issue by Anntoin** [okken/pytest-check#2]
When check catches a failure the logging isn't detailed. For example:
```
FAILURE: 
  integration/foo.py, line 123, in test_foo() -> check.equal(foo, bar)
AssertionError
```
Ideally would also see the specifics of the AssertionError but it seems that these are dropped in [log_failure](https://github.com/okken/pytest-check/blob/2e8bfafed8c77b725830b49dff49bca58c2e2c7f/src/pytest_check/plugin.py#L158) (I could be mistaken, but there doesn't seem to be a way to display verbose output).

**Comment by okken** [comment]
I’m now including the assert failure text. 
That’s kinda all that’s available. Hopefully that’s sufficient.
