### ISSUE TITLE
Other plugins might not get the failed status from pytest-check

### ISSUE THREAD

**Issue by Sup3rGeo** [okken/pytest-check#23]
Hi,

The `allure-pytest` plugin also uses the `pytest_runtest_makereport` plugin for getting test status, and it seems to be getting always a *pass* instead of a failure from `pytest-check`.

Examining the code, I see that `pytest-check` uses the option `tryfirst=True` in the `hookimpl` decorator:
https://github.com/okken/pytest-check/blob/823e6344cbf9987aa0e18e7a82b01d8b1e78c237/src/pytest_check/plugin.py#L7-L10

Ideally I believe that the `pytest-check` plugin should change the test status ASAP, in order to allow further plugins to have the correct status.

I naively assumed it was correct then to have `tryfirst=True`, however, because the hookwrapper implementation in `pytest-check` only uses the "teardown" part (after `yield`), it is actually the *last* plugin to run the teardown part.

Therefore, I believe it should be changed to `trylast=True` instead, so its teardown becomes the very first thing to be executed and assuring the correct test status as early as possible. Changing it locally here then yields the correct behaviour with `allure-pytest`.

I could create a PR w/ unit tests in case we agree on it. Thanks!

**Comment by okken** [comment]
This sounds like a cool approach to fix it.
I know this is old. Are you still up for the PR?

**Comment by okken** [comment]
fixed with 0.3.7
