### ISSUE TITLE
return True if assert passed

### ISSUE THREAD

**Issue by henrywah196** [okken/pytest-check#24]
when pytest_check failed it will return False. when it passed it will return None. Nice if it return True if check passed.

**Comment by joaonc** [comment]
This could be easily achieved adding `return True` after the function is evaluated:
```
def check_func(func):
    @functools.wraps(func)
    def wrapper(*args, **kwds):
        __tracebackhide__ = True
        try:
            func(*args, **kwds)
            return True
        except AssertionError as e:
            if _stop_on_fail:
                raise e
            log_failure(e)
            return False

    return wrapper
```

However, I don't think that's how it's supposed to work.
If you need to check if there are failures, you can use `get_failures()`, which returns a list of failures up to that point.
```
import pytest_check as check
...
check.check_methods.get_failures()
```

**Comment by okken** [comment]
I think this issue is valid, and should be fixed.
Thanks for reporting.
