### ISSUE TITLE
With pytest 6.0.0rc1, xfail shows up as xpass

### ISSUE THREAD

**Issue by okken** [okken/pytest-check#41]
A fix is possible, but I'm not sure if I can keep this plugin compatible with both pytest 4 & 5, and with pytest 6+ 
See https://github.com/pytest-dev/pytest/issues/7513 for more details.

Plugin still works as long as you don't use xfail on a test that also uses check.

**Comment by bskinn** [comment]
Aha, this is part of [what I saw](https://twitter.com/btskinn/status/1338236048892170240) in my testing today. It looked like xfails getting interpreted as xpasses, and vice versa.

**Comment by okken** [comment]
fixed with 0.4.0
