### ISSUE TITLE
Exception output is overwritten if there are failed checks in test

### ISSUE THREAD

**Issue by darthc9** [okken/pytest-check#43]
in the case of failed checks in the test, the hook pytest_runtest_makereport will overwrite report.longrepr instead of appending to it. but report.longrepr  hold the output to be printed for the exception. 

(if there are no failures naturally the hook does not overwrite this var and the output of the exception gets printed)

**Comment by okken** [comment]
seems bad. will try to look into soon-ish

**Comment by okken** [comment]
might be a dup of #44
