### ISSUE TITLE
Add support for pytest allure

### ISSUE THREAD

**Issue by aswinselva03** [okken/pytest-check#57]
pytest allure support as tests are failed but the checks are not getting displayed

Allure - 

![image](https://user-images.githubusercontent.com/36582181/113540478-dce21280-95fd-11eb-887a-54b454cdff40.png)

pytest html -
![image](https://user-images.githubusercontent.com/36582181/113540523-f08d7900-95fd-11eb-8fd3-6db3c5c525f9.png)

**Comment by jaimedelreyg** [comment]
Hi,

Please check my issue #52 . The pull request #53 related adds this functionality that you mention. Includes check error messages in allure.

Jaime.

**Comment by bondnotanymore** [comment]
Hi @jaimedelreyg I am facing a similar issue where I replace all my assert statements with check style statements.
But now when the test fails, allure report is unable to show it. 
With simple assert statements, it used to very well show that.

Will your fix also take care of that?? If yes, it will be awesome :) 

For eg. Will regular assert style statments in tests( NO pytest_check used):

Allure report clearly shows the assertion failure.

<img width="680" alt="Screenshot 2021-05-19 at 5 52 53 PM" src="https://user-images.githubusercontent.com/31071589/118812149-7114ea00-b8cb-11eb-9aeb-0206ab09bd7c.png">

However after implementing check style statements, assertion failures are missing for failed tests, which makes the use of this wonderful plugin unusable.

<img width="682" alt="Screenshot 2021-05-19 at 5 57 18 PM" src="https://user-images.githubusercontent.com/31071589/118812572-e2549d00-b8cb-11eb-9bcf-7a58abf0f193.png">

**Comment by okken** [comment]
I've reached out to Allure team to try to come up with a solution.
Adding extra logging does "fix" the allure thing in some instances, but degrades the experience for non-allure users.
It's important for me to fix this as well, but I don't know what the fix is yet.

**Comment by okken** [comment]
BTW, proposed fix does not fix everything, provides no tests, and duplicates error reporting on the CLI. 
I don't think that's a realistic fix.

**Comment by jaimedelreyg** [comment]
Hi guys,

@okken for non-allure users, they can avoid duplicated error messages modifying Python traceback print using pytest option `-tb` [https://docs.pytest.org/en/6.2.x/usage.html#modifying-python-traceback-printing](https://docs.pytest.org/en/6.2.x/usage.html#modifying-python-traceback-printing)

How we can manage the tests? I mean, we would need to test this feature with allure and getting errors in the allure's user interface. Sound like a manual test, but maybe I'm missing something.

@bondnotanymore #53 fix this for allure. I don't understand if you have another problem.

> Hi @jaimedelreyg I am facing a similar issue where I replaced all my assert statements with check style statements,
> Because now when the test fails, allure report is unable to show the failure logs itself, which defeats the whole purpose here :(
> With simple assert statements, it used to very well show that.
> 
> Will your fix also take care of that?? If yes, it will be awesome :)
> 
> For eg.
> **With regular assert style statments in tests( NO pytest_check used): Allure report clearly shows the assertion failure.**
> 
> <img alt="Screenshot 2021-05-19 at 5 52 53 PM" width="680" src="https://user-images.githubusercontent.com/31071589/118812149-7114ea00-b8cb-11eb-9aeb-0206ab09bd7c.png">
> 
> **However after implementing check style statements, assertion failures are missing for failed tests, which makes this wonderful plugin unusable.**
> 
> <img alt="Screenshot 2021-05-19 at 5 57 18 PM" width="682" src="https://user-images.githubusercontent.com/31071589/118812572-e2549d00-b8cb-11eb-9bcf-7a58abf0f193.png">
