### ISSUE TITLE
Setup docs under Sphinx

### ISSUE THREAD

**Issue by pauleveritt** [okken/pytest-check#59]
I'll make a PR to help on this, want to make a checklist for things that need to be done as well as have some discussion.

- [] Initial docs pages using MyST for Markdown
- [] `api.md` with sphinx.ext.autodoc
- [] GHA for publishing docs

## Questions

- Where do you want these hosted?
- Is everything "public"?
- Related: want to add some good docstrings, perhaps with the Google style (for sphinx.ext.napoleon formatting)
- You don't currently have type hints, if you plan to add them, I can setup the autodoc extension for that

**Comment by okken** [comment]
Thanks Paul. I don't know the answers to any of those questions. 
- Docstrings need to be in markdown. Not sure what Google docstring style is.
- type hints. probably a good idea.
- public: I'll have to look a bit
- hosted: ¯\_(ツ)_/¯ Maybe GH pages?

**Comment by joaonc** [comment]
Some suggestions here:

1. This project is small enough that doesn't justify separate documentation. The Readme.MD is enough.
2. If there was to be documentation, I would suggest using `mkdocs`, especially with the `mkdocs-material` plugin, which makes writing docs using Markdown (on steroids) super easy **and** equally easy to deploy to GitHub Pages (just run `mkdocs gh-deploy`). No need to host and deployment is a one liner.
3. This ticket should be closed.

**Comment by okken** [comment]
Agree with @joaonc . README is fine.
