### ISSUE TITLE
Using `--showlocals` does not print variables

### ISSUE THREAD

**Issue by saveshodhan** [okken/pytest-check#73]
When `pytest` is run with `--showlocals` switch, we can see the variables printed whenever the `assert` statement fails.
But when using any `check` methods, they are not printed.

Am I missing out on something?

pytest command: `pytest --showlocals -vvv -rA tests/test_me.py`

### case 1 (with `assert`):
```python
def test_me:
    a = 0
    b = 1
    assert a
```
### output:
```
tests/test_me.py::test_me FAILED                                                        [100%]

========================================== FAILURES ===========================================
___________________________________________ test_me ___________________________________________

    @pytest.mark.galaxy("dum")
    @pytest.mark.integration_name("dum")
    def test_me():
        a = 0
>       assert a
E       assert 0

a          = 0
b          = 1

tests/test_me.py:8: AssertionError
=================================== short test summary info ===================================
FAILED tests/test_me.py::test_me - assert 0
====================================== 1 failed in 0.14s ======================================
```
### case 2 (with `check`):
```python
def test_me:
    a = 0
    b = 1
    check.is_true(a)
```
### output:
```tests/test_me.py::test_me FAILED                                                        [100%]

========================================== FAILURES ===========================================
___________________________________________ test_me ___________________________________________
FAILURE: 
assert False
 +  where False = bool(0)
tests/test_me.py:8 in test_me() -> check.is_true(a)
------------------------------------------------------------
Failed Checks: 1
=================================== short test summary info ===================================
FAILED tests/test_me.py::test_me
====================================== 1 failed in 0.18s ======================================
```

**Comment by Kev-ASU** [comment]
Also having this issue. Is there any work around currently?  Assert shows all locals, but checks do not. 

```python
>>> pytest.main(["tests/test_me.py::test_2", "--showlocals"])
```

```bash
============================= FAILURES ============================= 
______________________________ test_2 ______________________________
FAILURE: 
tests/test_me.py:3 in test_2() -> check.is_true(False), f" {a}"

```

It should show the variable `a` to equal `0`, using the same syntax as the above comment.

**Comment by okken** [comment]
I agree that it would be nice if showlocals worked with this plugin.
If you'd like to work on a PR for this, that'd be cool.

**Comment by saveshodhan** [comment]
let me give it a try.. :v:

**Comment by okken** [comment]
--slowlocals is implemented in pytest as part of the traceback handling.
See repr_locals call in repr_traceback_entry()

Since pytest-check doesn't use pytest traceback mechanism, this isn't going to work.
It would be possible to re-implement the functionality in pytest-check, but that doesn't seem fun.

As a workaround, you can add `assert not check.any_failures()` to the function where you care about seeing the local values. 

Closing this for now, as there is a workable workaround.
