### ISSUE TITLE
check_func() should be exported. I'd like to use it on my own assert functions.

### ISSUE THREAD

**Issue by ZbigniewRA** [okken/pytest-check#8]
check_func() decorator is very useful on it's own (as evidenced by it's usage in the library itself!).
I would like to be able to decorate my own helper functions with it.

I don't want to rewrite helper assert functions from using 'asserts' to using 'expects', because I don't want to change their meaning globally. But in certain contexts I would like to make them into 'expects'.
This will greatly improve modularity and composability of my test code.

After that if would be good to have it (at least optionally) also convert pytest's OutcomeExceptions into non-fatal errors.

**Comment by okken** [comment]
1. I like the idea of exposing the check_func() decorator.

2. I'm not really sure what else you are asking. Could you be more specific?

**Comment by okken** [comment]
The decorator `@check_func` is exposed in 0.3.2.
Please open other issues if there are further things you'd like to see.

**Comment by ZbigniewRA** [comment]
Thanks!
The second point was about catching exceptions from pytest.fail() and treating them the same way as AssertionException. It was just a thought.
