### ISSUE TITLE
Idea: context manager API

### ISSUE THREAD

**Issue by ionelmc** [okken/pytest-check#9]
So one thing in pytest-check that is reminiscent of unittest and nose is the assertion api. While it should work fine with pytest's assertion rewriter you still need to remember what the method name is. Is it `check.less` or `check.less_than`? Is it `check.equal` or `check.is_equal`? You can never tell.

So an alternative:
```python
with check: assert a < 1
with check: assert 1 < a < 10
```
Context managers can "silence" exceptions by returning True in `__exit__`.

**Comment by okken** [comment]
This is brilliant

**Comment by okken** [comment]
0.3.3 added a `check()` context manager.
So this now works:

```
with check(): assert a < 1
with check(): assert 1 < a < 10
```

**Comment by okken** [comment]
Also, kinda really stoked that you took a look at the plugin.
I've learned a lot from you over the past few years.

**Comment by ionelmc** [comment]
Heh thanks. Not wanting to nitpick but I had hoped for a singleton-ish api (no function call, as it seems unnecessary). I'll make a PR to fix it what do you think?

**Comment by ionelmc** [comment]
Another thing that I noticed - only AssertionErrors are collected - is that intentional?

**Comment by okken** [comment]
I like the Singleton idea. Wasn’t sure how to accomplish it. So please, PR

**Comment by okken** [comment]
Only catching assertions.  Ya. It was intentional. But maybe not in line with normal pytest behavior of all exceptions causing failure. 

Do you have an opinion?

**Comment by ionelmc** [comment]
So now that I think of it more, I'd prolly woulnd't like seeing dozen undefined variable failures, so it's fine as it is now.
