### ISSUE TITLE
Failure message color in pytest-html ?

### ISSUE THREAD

**Issue by ant1kdream** [okken/pytest-check#93]
Hello. I found that pytest-check do not have classic red color after exporting stdout to html using pytest-html.
Below examples of same run with pytest-check and pytest-assume

here is grey color of pytest-check:
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/46380751/195078500-7c5fdab0-0d41-4327-97f3-88e016c79bc1.png">

comparing with pytest-assume here is red color:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/46380751/195078821-61da4ac8-f69f-47b2-ab6b-1cb154e0c45a.png">

Nothing changed between these screenshots instead of replacing with assume: and with check:
Do you have any option or suggestion how to make it classic red color? Thx

**Comment by jeffwright13** [comment]
Those look like two totally different results to me, and it's not clear if they should both be colored the same or not. Can you provide the test that resulted in this? Or reproduce with a different test? I can provide you with sample tests that give all the different outcomes if you like.

**Comment by ant1kdream** [comment]
@jeffwright13 Yes, sure. It's easily reproducing. Below comparing outputs from classic assert, pytest-assume and pytest-check and all results exported to pytest-html with next args:

--html=report.html --self-contained-html

```
from pytest_assume.plugin import assume
from pytest_check import check


def test_assert():
    assert 2 < 1, 'some message'

def test_assume():
    with assume: assert 2 < 1, 'some message'

def test_check():
    with check: assert 2 < 1, 'some message'
```

in html we see that classic assert and pytest-assume have classic red color in AssertionError message, except of pytest-check
<img width="719" alt="image" src="https://user-images.githubusercontent.com/46380751/195517172-c858068d-5683-4b3f-9205-a8511e41e0b7.png">

**Comment by jeffwright13** [comment]
Oh, I see what you are saying now. I didn't pick up on the fact that you're using different plugins, each of which changes the output in some way.

I'm sure @okken is more than capable of figuring out the issue, so I will just watch from the sidelines. I'd take a stab at it myself, but it does take time to assimilate someone else's code, and I'm not super familiar with this plugin.

**Comment by okken** [comment]
I'm open to consider PRs for the change.

**Comment by okken** [comment]
This is a good idea. 
working on a solution.

**Comment by okken** [comment]
color added in https://github.com/okken/pytest-check/pull/94

**Comment by okken** [comment]
I haven't  checked the html output

**Comment by okken** [comment]
My changes don't help any with the html output from pytest-html.

**Comment by okken** [comment]
I actually think I made things worse for pytest-html.
So if using pytest-html, I recommend --color=no until we get this sorted out.

**Comment by jeffwright13** [comment]
This makes me curious about how my plugin will handle this situation. I'll give it a test.

**Comment by okken** [comment]
probably pushing to main today

**Comment by okken** [comment]
This would require digging into pytest-html, maybe, which I'm not interested in doing at this time.

**Comment by okken** [comment]
Closing for now. Feel free to bring up the issue again if you've got any thoughts on how to implement it.
